sudo: required
services: 
  - docker

before_install:
  - docker build -t akalve/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akalve/docker-react npm run test

deploy: 
  provide: elasticbeanstalk
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  region: us-east-1
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-599169218874"
  bucket_path: "docker-react"
  on: 
    branch: master